import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

// Styles
import './globals.css';

// Components
import Nav from '@/components/Nav';

// Context
import { GTagProvider } from '@/context/GTagContext';

export const metadata: Metadata = {
	title: 'Next App Directory - gtag',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<GTagProvider tagId={process.env.GTAG_ID}>
				<body className={GeistSans.className}>
					<Nav />
					{children}
				</body>
			</GTagProvider>
		</html>
	);
}
